backend:
  name: git-gateway
  # branch: master # Branch to update (optional; defaults to master)
  branch: vite # Branch to update (optional; defaults to master)

# Please run 'npx netlify-cms-proxy-server' for local backend
local_backend: true

media_folder: public/media
public_folder: /media

i18n:
  # Required and can be one of multiple_folders, multiple_files or single_file
  # multiple_folders - persists files in `<folder>/<locale>/<slug>.<extension>`
  # multiple_files - persists files in `<folder>/<slug>.<locale>.<extension>`
  # single_file - persists a single file in `<folder>/<slug>.<extension>`
  structure: single_file

  # Required - a list of locales to show in the editor UI
  locales: [en, fr]

  # Optional, defaults to the first item in locales.
  # The locale to be used for fields validation and as a baseline for the entry.
  default_locale: en

collections:
  - name: 'stories'
    label: 'Stories'
    folder: 'public/cms-data/stories'
    format: 'json'
    create: true
    i18n: true
    editor:
      preview: false
    identifier_field: id
    fields:
      - {label: 'Id (never change this, only set a unique value at creation)', name: id, widget: string, hint: 'At creation, the id will determine the name of the file where the story is stored.' }
      - { label: 'Url path', name: 'url-path', widget: 'string', hint: 'the path to this story after the site name datastories.com/en/[url path]' }
      - { label: 'Title', name: 'title', widget: 'string', i18n: true }
      - { label: 'Publish Date', name: 'date', widget: 'datetime', i18n: true }
      - { label: 'Description', name: 'description', widget: 'string', i18n: true }
      - { label: 'Body', name: 'body', widget: 'markdown', i18n: true }

  - name: 'configuration'
    label: 'Configuration'
    files:
      - name: 'visible-stories'
        label: 'Visible stories'
        file: public/cms-data/visible.stories.json
        i18n: false
        fields:
          - name: visible-stories-list
            label: 'Visible Stories'
            widget: 'list'
            summary: '{{fields.title}}'
            fields:
              - name: story
                label: Story
                widget: relation
                collection: stories
                value_field: id
                display_fields: ['title']
                search_fields: ['title']
                multiple: false
